[package]
name = "test-nft-token"
version = "0.1.0"
authors = ["Illia Polosukhin <illia.polosukhin@gmail.com>", "Rashi Abramson <roshkins@gmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]


[dependencies]
near-sdk = "4.0.0-pre.2"
near-contract-standards = "4.0.0-pre.2"
